import axios from "axios";

// Create an instance of axios
const openai = axios.create({
    baseURL: "https://api.openai.com/v1", //base url
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${import.meta.env.VITE_OPENAI_API_KEY}`,
    },
  });
  
  // Async function that takes a prompt (user input) and fetches a response from OpenAI
  export const fetchChatGPTResponse = async (prompt) => {
    try {
      // Post request
      const response = await openai.post("/chat/completions", {
        model: "gpt-4o-mini",
        messages: [{ role: "user", content: prompt }], // prompt = text from user
        max_tokens: 100,
      });
  
      return response.data.choices[0].message.content; // return text generated by ChatGPT
    } catch (error) {
        // Error handling:
      console.error("Error fetching response:", error);
      return "Something went wrong!";
    }
  };